language: python
python:
    - "2.7"

# Use docker container infrastructure.
sudo: false

# Cache the pip directory. "cache: pip" doesn't work due to install override. See https://github.com/travis-ci/travis-ci/issues/3239.
cache:
  directories:
    - $HOME/.cache/pip
install:
    - pip install --upgrade pip wheel
    - make requirements
script:
    - make validate
branches:
    only:
        - master
